# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

require File.dirname(__FILE__) + '/../lib/todo_next.rb'

class TodoNext::Tree
  def to_hash
    {
        :children => children.collect{|ch| ch.to_hash }
    }
  end

  class OL

    def to_hash
      {   :type => :ol,
          :text => text,
          :children => children.collect{|ch| ch.to_hash }
      }
    end
  end
  class LI
    def to_hash
      {   :type => :li,
          :text => text
      }
    end
  end
end

def parsed_result(source)
  TodoNext::Parser.parse(source).to_hash[:children]
end

def result_should_be(expected)
  parsed_result(@source).should == expected
end
